### PR TITLE
Custom host option

### LINKED ISSUE #77: REST API Gateway problem
If I have a REST API Gateway deployed for my lambda functions, when the swagger is deployed, new HTTP Gateway will be created with different domain, so all my endpoints inside the documentation will have the wrong domain.

### PR DESCRIPTION
**Pull request by sebastijan94**
Closes #77

### CODE REVIEW

File: src/ServerlessAutoSwagger.ts [hunk 1]
```diff
@@ -104,6 +104,7 @@ export default class ServerlessAutoSwagger {
     const autoswagger = this.serverless.service.custom?.autoswagger ?? {};
 
     if (autoswagger.basePath) this.swagger.basePath = autoswagger.basePath;
+    if (autoswagger.host) this.swagger.host = autoswagger.host;
```
Comment (bfaulk96) [inline src/ServerlessAutoSwagger.ts:107]: Could you add this test case to the unit test `should use overrides if specified`? Should be as simple as going into `tests/ServerlessAutoSwagger.test.ts` and adding `host: 'some-host'` below line [821](https://github.com/SamWSoftware/serverless-auto-swagger/blob/3ccd0394bca8f7e89dbcdc86db1241c7c3f529e3/tests/ServerlessAutoSwagger.test.ts#L821), then the same below line [839](https://github.com/SamWSoftware/serverless-auto-swagger/blob/3ccd0394bca8f7e89dbcdc86db1241c7c3f529e3/tests/ServerlessAutoSwagger.test.ts#L839)

**Comment by sebastijan94** [comment]
Added the requested things.

**Review by bfaulk96 — APPROVED** [review]
